package task.healthyhabits.exceptions;


public enum ErrorCode {

    BAD_CREDENTIALS,
    ACCESS_DENIED,
    INVALID_PASSWORD,

    HABIT_NOT_FOUND,
    DUPLICATE_FAVORITE,
    REMINDER_TIME_CONFLICT,
    ROUTINE_STATE_INVALID,

    CONSTRAINT_VIOLATION,
    ILLEGAL_ARGUMENT,

    DATA_INTEGRITY_VIOLATION,

    INTERNAL_ERROR;
}